apiVersion: v2
name: my-app-chart
description: A Helm chart for the complete n8n, discord, and minio application stack.

# A chart can be either an 'application' or a 'library' chart.
# Application charts are installable, while library charts provide templates.
# It is recommended to set this to 'application' unless you are creating
# a library chart.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates.
version: 0.1.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application.
appVersion: "1.0.0"
