# templates/04-discord.yml
apiVersion: v1
kind: Service
metadata:
  name: discord-svc
spec:
  ports:
  - port: 8000
  selector:
    app: discord
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: discord-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discord
  template:
    metadata:
      labels:
        app: discord
    spec:
      containers:
      - name: discord
        image: {{ .Values.discord.image | quote }}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: app-config
