# templates/05-minio.yml
apiVersion: v1
kind: Service
metadata:
  name: minio-svc
spec:
  ports:
    - name: api
      port: 9000
    - name: console
      port: 9001
  selector:
    app: minio
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minio-ss
spec:
  serviceName: "minio-svc"
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
      - name: minio
        image: {{ .Values.minio.image | quote }}
        imagePullPolicy: IfNotPresent
        command:
        - minio
        - server
        - /data
        - --console-address
        - ":9001"
        envFrom:
        - secretRef:
            name: minio-secret
        env:
        - name: MINIO_SERVER_URL
          value: "https://{{ .Values.domain }}{{ .Values.minio.consolePath }}"
        ports:
        - containerPort: 9000
        - containerPort: 9001
        volumeMounts:
        - name: minio-storage
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: minio-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: {{ .Values.minio.storage | quote }}
